#!/usr/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2026-present Guillon Flavien

run_hook() {
    local FINAL_ROOT="/new_root"
    local TEMP_DISK="/mnt/boot_disk_temp"
    
    # 1. Montage temporaire du disque physique
    local root_dev=$(resolve_device "$root")
    mkdir -p "$TEMP_DISK"
    mount "$root_dev" "$TEMP_DISK"

    # 2. Résolution dynamique des chemins
    local boot_img=$(cat /proc/cmdline | tr ' ' '\n' | sed -n 's/^BOOT_IMAGE=//p')
    local boot_dir=$(dirname "$boot_img")
    local target_name=$(getarg mnt)
    
    # 3. APPEL DE L'UTILITAIRE
    /usr/bin/mnt-stackfs \
        --type move \
        --boot "$boot_dir" \
        --target "$target_name" \
        --src "$TEMP_DISK" \
        --dest "$FINAL_ROOT" \
        --log "${TEMP_DISK}${boot_dir}/.stackfs.log"

    # 4. VERIFICATION ET SAUT
    if [ ! -x "${FINAL_ROOT}/sbin/init" ]; then
        echo "ERREUR : /sbin/init non trouvé dans ${FINAL_ROOT}"
        launch_interactive_shell
    fi

    # Debug (à supprimer plus tard)
    launch_interactive_shell

    [ -f /usr/bin/rdlogger_stop ] && rdlogger_stop
    
    echo "::: StackFS : Switching root :::"
    exec env -i "TERM=$TERM" /usr/bin/switch_root "$FINAL_ROOT" "/sbin/init"
}
