#!/usr/bin/bash

run_hook() {
    local FINAL_ROOT="/new_root"
    local TEMP_DISK="/mnt/boot_disk_temp"
    
    # 1. Extraction des paramètres de la ligne de commande
    local root_dev=$(resolve_device "$root")
    # On cherche l'éventuel subvolume (ex: subvol=@)
    local root_subvol=$(cat /proc/cmdline | tr ' ' '\n' | sed -n 's/^subvol=//p')
    
    local mount_opts=""
    [ -n "$root_subvol" ] && mount_opts="-o subvol=$root_subvol"

    echo "::: Montage du disque physique ($root_dev) :::"
    mkdir -p "$TEMP_DISK"
    mount $mount_opts "$root_dev" "$TEMP_DISK"

    # 2. Résolution des chemins de boot
    # On récupère BOOT_IMAGE (souvent /@/boot/vmlinuz-linux)
    local boot_img=$(cat /proc/cmdline | tr ' ' '\n' | sed -n 's/^BOOT_IMAGE=//p')
    # On nettoie le préfixe du subvolume pour mnt-stackfs
    # (Si boot_img commence par /@/, on l'enlève pour avoir le chemin relatif au point de montage)
    local boot_dir=$(dirname "$boot_img" | sed "s|^/${root_subvol}||")
    local target_name=$(getarg mnt)
    
    [ -z "$target_name" ] && target_name="stackfs"

    echo "::: Lancement de l'orchestrateur StackFS :::"
    if [ -f "/usr/bin/mnt-stackfs" ]; then
        /usr/bin/mnt-stackfs \
            --type move \
            --boot "$boot_dir" \
            --target "$target_name" \
            --src "$TEMP_DISK" \
            --dest "$FINAL_ROOT" \
            --log "${TEMP_DISK}${boot_dir}/.stackfs.log"
    else
        echo "ERREUR CRITIQUE : /usr/bin/mnt-stackfs est introuvable dans l'initramfs !"
        launch_interactive_shell
    fi

    # 3. Vérification finale
    if [ ! -x "${FINAL_ROOT}/sbin/init" ]; then
        echo "ERREUR : /sbin/init non trouvé dans ${FINAL_ROOT}"
        echo "Contenu de ${FINAL_ROOT} :"
        ls -F "${FINAL_ROOT}"
        launch_interactive_shell
    fi

    echo "::: StackFS : Switching root :::"
    echo "=> Type exit to switch."
    launch_interactive_shell
    
    # On s'assure que les dossiers vitaux sont prêts pour le switch
    exec env -i "TERM=$TERM" /usr/bin/switch_root "$FINAL_ROOT" "/sbin/init"
}
